# @package _global_
datamodule:
  _target_: dpr_scale.datamodule.dpr.DenseRetrieverPassagesDataModule
  test_path: /storage/ukp/work/cai_e/instruction_pir/instruct-dense-retrieval/data/msmarco.instruct.dev.query.jsonl
  test_batch_size: 1
  use_title: false
